name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Force Git to use HTTPS for submodules
            run: git config --global url."https://github.com/".insteadOf "git@github.com:"
          - name: Update submodules
            run: |
              git submodule sync
              git submodule update --init --recursive --remote
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment3
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Checkout Repository
          - uses: actions/checkout@v4
            with:
              fetch-depth: 1
          - name: Fix Git Lock Issue
            run: |
              LOCK_FILE="/github/home/assignments-3-and-later-beaspin/linux-stable/.git/index.lock"
              if [ -f "$LOCK_FILE" ]; then
                echo "Removing stale git lock file..."
                rm -f "$LOCK_FILE"
              fi
          - name: Install Required Dependencies
            run: |
              sudo apt update &&
              sudo apt install -y gcc-aarch64-linux-gnu qemu-system-aarch64
          - name: Run full test
            run: bash -x ./full-test.sh
