name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - name: Install SSH Client
            run: |
              apt-get update && apt-get install -y openssh-client
          - name: Debug SSH Installation
            run: |
              which ssh
              ssh -V
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Test SSH Connection
            run: ssh -T git@github.com || true
          - name: Run unit test
            run: ./unit-test.sh
