name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 240
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
               ssh-pubblic-key: ${{ secrets.SSH_PUBBLIC_KEY }}
          - name: Set FORCE_UNSAFE_CONFIGURE
            run: |
              export FORCE_UNSAFE_CONFIGURE=1
              echo "FORCE_UNSAFE_CONFIGURE=1" >> $GITHUB_ENV
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: |
              export SKIP_BUILD="1"
              export DO_VALIDATE="0"
              ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
