name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Force Git to use HTTPS for submodules
            run: git config --global url."https://github.com/".insteadOf "git@github.com:"
          - name: Update submodules
            run: |
              git submodule sync
              git submodule update --init --recursive --remote
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment3
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Fix Git Lock Issue
            run: |
              LOCK_FILE="/github/home/assignments-3-and-later-beaspin/linux-stable/.git/index.lock"
              if [ -f "$LOCK_FILE" ]; then
                echo "Removing stale git lock file..."
                rm -f "$LOCK_FILE"
              fi
              echo "Resetting repository to avoid conflicts..."
              git reset --hard HEAD
              git clean -fdx
          - name: Install Required Dependencies
            run: |
              sudo apt update &&
              sudo apt install -y gcc-aarch64-linux-gnu qemu-system-aarch64 curl
          - name: Download Kernel Image
            run: |
              IMAGE_URL="https://raw.githubusercontent.com/cu-ecen-aeld/assignments-3-and-later-beaspin/master/Image"
              IMAGE_PATH="/github/home/assignments-3-and-later-beaspin/Image"
              echo "Downloading kernel image..."
              curl -L -o "$IMAGE_PATH" "$IMAGE_URL"
              if [ -f "$IMAGE_PATH" ]; then
                echo "Kernel image downloaded successfully"
              else
                echo "Kernel image download failed"
                exit 1
              fi
          - name: Set Kernel Image Permissions
            run: chmod +x /github/home/assignments-3-and-later-beaspin/Image
          - name: Download Initramfs Image
            run: |
              INITRD_URL="https://raw.githubusercontent.com/cu-ecen-aeld/assignments-3-and-later-beaspin/master/initramfs.cpio.gz"
              INITRD_PATH="/github/home/assignments-3-and-later-beaspin/initramfs.cpio.gz"
              echo "Downloading initramfs image from: $INITRD_URL"
              curl -L -o "$INITRD_PATH" "$INITRD_URL"
              if [ -f "$INITRD_PATH" ]; then
                 echo "Initramfs image downloaded successfully!"
              else
                 echo "Initramfs image download failed"
                 exit 1
              fi
          - name: Run full test
            run: bash -x ./full-test.sh
